# Site settings
title: apporc's
email: apporc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    I am somebody.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://apporc.org" # the base hostname & protocol for your site
twitter_username: apporc
github_username:  apporc

# Build settings
markdown: kramdown
